version: '3.1' # specify docker-compose version

services:

  ui:
    image: test/webui
    build: 
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
      - nginx-proxy
    ports:
      - "3000:3000"
      